### ISSUE TITLE
Explicit imports

### ISSUE THREAD

**Issue by eightyeight** [parsonsmatt/servant-persistent#1]
What's your feeling on explicit or qualified imports? I much prefer explicit imports in learning contexts, so learners can see easily what modules export what. I'm happy to make a PR if you'd prefer not to do it yourself!

**Comment by parsonsmatt** [comment]
I completely agree! I'm refining the code and writing a blog post to accompany it. If you'd like to contribute in anyway, I'd appreciate it :smile:

**Comment by parsonsmatt** [comment]
I've made most of the imports explicit now, so I'll close this out. Thanks for bring it up!

**Comment by eightyeight** [comment]
Can confirm, issue is fixed for me :wink:
