### ISSUE TITLE
Make this work with servant == 0.5

### ISSUE THREAD

**Issue by psibi** [parsonsmatt/servant-persistent#4]
I can give you a patch if you are interested, but your associated blog post may get out of sync.

**Comment by parsonsmatt** [comment]
I actually plan on updating and redoing the blog post for servant 0.5. There are a few other changes I want to make (`newtype` the App monad, use `mtl` style classes, a less-awkward conversion from `readerToEither`, etc).

**Comment by parsonsmatt** [comment]
I've updated the blog post to point to the 0.4 branch now, and the master branch works on 0.5.
