### ISSUE TITLE
Upgrading to GHC 9.4.x 

### ISSUE THREAD

**Issue by sigrdrifa** [parsonsmatt/servant-persistent#48]
Just stumbled across this project and I was wondering if anyone has had any luck building the project with a newer resolver or with cabal and a newer version of GHC.

I tried building it with cabal targeting GHC2021 and ghc version 9.4.8 but several of the dependencies failed to resolve, even when loosening the constraints on the versions, packages like ekg fail to build due to dependency issues.

Would appreciate if someone could point me in the direction of any guidance/resource on how to remedy this.

Thanks!

**Comment by sigrdrifa** [comment]
I managed to manually upgrade the libraries to make it compile on GHC 9.4.8 and using GHC2021.

The only thing that didn't gracefully upgrade was ekg so I ended up removing the metrics as I didn't need it.

Thanks for this project!

**Comment by panserbjorn** [comment]
@sigrdrifa would you mind sharing a fork or the process for upgrading the libraries to work with GHC 9.4.x? 😄 I'm facing the same issue myself right now.

**Comment by sigrdrifa** [comment]
@panserbjorn I ended up creating a starter kit template that is based on this that uses GHC 9.4.x or 9.6.x - you can check it out here: https://github.com/eldr-io/hastl 

It uses the same base so if you want you can strip out the updated libraries and it should work :) hope that helps!
