### ISSUE TITLE
Actual testing examples

### ISSUE THREAD

**Issue by Superpat** [parsonsmatt/servant-persistent#9]
The blog posts are very good introductions to using persistent with servant, and the repo serves as a great template from which to start. The only thing I feel is missing is examples of actual tests, as a relative newbie I'm not exactly sure how I would test the persistent - servant interaction.

**Comment by parsonsmatt** [comment]
That's a great suggestion! One of the nice things about Servant is that the handlers are *just* functions in some monad. Since `newtype App a = App { runApp :: ReaderT Config (ExceptT ServantErr IO) a }`, we can define a function:

```haskell
appToIO :: Config -> App a -> IO (Either ServantErr a)
```

that lets you run any `App` function and get the stuff out of it. From there, you can test it like you would any `IO` function.

**Comment by Superpat** [comment]
Cool, will try that out then! Maybe even send a pull request if I manage to wrap my head around it properly.

**Comment by rpereira** [comment]
Hi,

I'm struggling a bit trying to write test cases for the current API. @parsonsmatt can you please provide us with a more detailed explanation and/or examples on how to do it? Thanks in advance.

**Comment by parsonsmatt** [comment]
Can you expand on what you're struggling with?

**Comment by rpereira** [comment]
I'm interested in writing tests for the current API. My main struggles are (1) actually setting up the test environment and (2) how to structure a test case. As per (1), it includes using the test environment specified in Config.hs and connect to the database.

**Comment by rpereira** [comment]
Hey, @parsonsmatt. I've trying to simply connect to a test database (and hopefully do simple tests such as insert a User and check if it is there) on the `servant-persistent/test/ApiSpec.hs` file but failed miserably. Can you please share your thoughts on how to set this up? Thanks.

**Comment by parsonsmatt** [comment]
So, currently, [this is the function that sets up the database for test](https://github.com/parsonsmatt/servant-persistent/blob/master/src/Config.hs#L63-L65). It expects to be able to connect with a connection string like [this](https://github.com/parsonsmatt/servant-persistent/blob/master/src/Config.hs#L108-L109)], so `perservant-test` needs to be available for that user.

`HSpec` has [a set of functions](https://hackage.haskell.org/package/hspec-core-2.4.3/docs/Test-Hspec-Core-Hooks.html#v:beforeAll) for initializing stuff. So you can write something like

```haskell
spec :: Spec
spec = beforeAll initializeConfig $ do
  describe "Insert Users" $ do
    it "can connect to database" $ \config -> do
      let user = User "hello" "foobar"
      mresult <- runApp' config $ do
        Sql.insert user
        Sql.selectFirst (UserName ==. "Hello")
      mresult `shouldBe` Just user
```

The `SpecWith a` means that the `it` specs expect a *lambda* of type `a` in addition to the assertions/expectations.

`initializeConfig` should set up the test database and provide the config for the application. `runApp' :: Config -> App a -> IO a`, which would just throw the exceptions from ServantErrors.

You can also use `around setupTeardown`, where

```haskell
setupTeardown runTestWith = do
  cfg <- initializeConfig
  runTestWith cfg
  cleanupDatabase cfg
```

**Comment by rpereira** [comment]
Thanks for your time @parsonsmatt, much appreciated!

**Comment by parsonsmatt** [comment]
@StevenXL and @bchase have fixed this up :)
